---
- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_os_family }}.yml"

- name: OS is supported
  assert:
    that: logentries_os_supported == True

- name: Add APT keys
  apt_key: id={{ item.id }} {{ item.method }}={{ item.value }} state=present
  with_items: logentries_apt_keys
  when: ansible_os_family == "Debian"

- name: Add APT repositories
  apt_repository: repo="{{ item }}" update_cache=yes
  with_items: logentries_apt_repositories
  when: ansible_os_family == "Debian"

- name: Install packages
  apt: name={{ item }} state=present
  with_items: logentries_packages
  when: ansible_os_family == "Debian"

- name: Check if host is registered
  command: le whoami
  register: result
  ignore_errors: true
  changed_when: false

- name: Register host
  shell: "le register --name={{ ansible_fqdn }} --hostname={{ ansible_fqdn }} --yes --account-key={{ logentries_account_key }}"
  when: result|failed

- name: Install logentries daemon
  apt: name={{ logentries_daemon_package }} state=present

- name: Follow logs
  logentries: path={{ item.path }} state={{ item.state | default('present') }}
  notify:
  - Restart logentries
  with_items: logentries_logs
