---
- name: Restart logentries
  service: name={{ logentries_service }} state=stopped
  notify: 
    - Sleep logentries restarter

- name: Sleep logentries restarter
  wait_for:
    path: /var/lrun/logentries.pid
    state: absent
  notify: 
    - Start logentries restarter

- name: Start logentries restarter
  service: name={{ logentries_service }} state=started
