---
# Logentries is unable to cleanup it's own pid file when shutdown via systemd
- name: Restart logentries
  service: name={{ logentries_service }} state=stopped
  notify: 
    - Sleep logentries restarter

- name: Sleep logentries restarter
  wait_for: path=/var/run/logentries.pid state=absent
  notify: 
    - Start logentries restarter

- name: Start logentries restarter
  service: name={{ logentries_service }} state=started
